  - name: Update APT package cache
    apt: update_cache=yes cache_valid_time=600 force_apt_get=yes

  - name: Upgrade APT to the latest packages
    apt: upgrade=dist force_apt_get=yes
    register: apt_result
    force_apt_get: yes

  - name: Install a list of packages
    command: apt-get install -y jq dnsutils ctop
    register: apt_result
    changed_when: "'packages will be installed' in apt_result.stdout"

  - name: Autoremove unused packages
    command: apt-get -y autoremove
    register: apt_result
    changed_when: "'packages will be REMOVED' in apt_result.stdout"

  - name: Purge residual kernel packages
    shell: apt-get remove -y --purge $(dpkg -l | grep "^rc\s*linux-image-" | awk '{print $2}' | tr '\n' ' ')
    register: apt_result
    changed_when: "'packages will be REMOVED' in apt_result.stdout"
